<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    </head>

    <body>
        <div>
            <span class="p_orbBoxTitle">Security</span>
        </div>
        <br/>
        <div class="floatstop"></div>
        <div id="divOrbTopL" >
            <div id="divShiftOrbButton" style="width: 100px;">
                <input type="button" id="shift_security_button" name="shift_security_button" value="At Home" alt="At Home" class="p_btn p_btnMnormal" onclick="setShiftState('summary/changeMode.jsp','','','11111111-2222-3333-4444-555555555555');" onmouseover="javascript:btnHover(this,'M')" onmouseout="javascript:btnNormal(this,'M')" onmousedown="javascript:btnDown(this,'M')" onmouseup="javascript:btnNormal(this,'M')"  data-fitLabel="shrink"/><style type="text/css">#testSizeshift_security_button {position: absolute; visibility: hidden; height: auto; width: auto; white-space: nowrap; min-width: 0}</style><div id="testSizeshift_security_button" class="p_btn p_btnMnormal" >At Home</div>
            </div>
        </div>
        <div id="divOrbTopC">
            <div id="divOrb" class="p_orb">
                <a href="../history/history.jsp?filter=All&deviceFilter=&timefilter=24" title="Security Panel History">
                    <canvas id="ic_orb"
                        orb="disarmed"
                        numOfTroubles="0"
                        numOpen="0"
                        numMotion="0"
                        class="p_ic_orb"
                        width="100"
                        height="100"
                        aria-label="Security Panel History"
                        role="img">
                    </canvas>
                </a>
            </div>
        </div>
        <div id="divOrbTopR">
            <div id="divOrbSecurityButtons">
            <div  /><input type="button" id="security_button_0" name="security_button_0" value="Arm Away" alt="Arm Away" class="p_btn p_btnMnormal" onclick="setArmState('quickcontrol/armDisarm.jsp','Arming Away','0','2','false','href=rest/adt/ui/client/security/setArmState&armstate=off&arm=away&sat=11111111-2222-3333-4444-555555555555')" onmouseover="javascript:btnHover(this,'M')" onmouseout="javascript:btnNormal(this,'M')" onmousedown="javascript:btnDown(this,'M')" onmouseup="javascript:btnNormal(this,'M')"  data-fitLabel="ellips"/><style type="text/css">#testSizesecurity_button_0 {position: absolute; visibility: hidden; height: auto; width: auto; white-space: nowrap; min-width: 0}</style><div id="testSizesecurity_button_0" class="p_btn p_btnMnormal" >Arm Away</div></div><div style = "margin-top: 6px;" /><input type="button" id="security_button_1" name="security_button_1" value="Arm Stay" alt="Arm Stay" class="p_btn p_btnMnormal" onclick="setArmState('quickcontrol/armDisarm.jsp','Arming Stay','1','2','false','href=rest/adt/ui/client/security/setArmState&armstate=off&arm=stay&sat=11111111-2222-3333-4444-555555555555')" onmouseover="javascript:btnHover(this,'M')" onmouseout="javascript:btnNormal(this,'M')" onmousedown="javascript:btnDown(this,'M')" onmouseup="javascript:btnNormal(this,'M')"  data-fitLabel="ellips"/><style type="text/css">#testSizesecurity_button_1 {position: absolute; visibility: hidden; height: auto; width: auto; white-space: nowrap; min-width: 0}</style><div id="testSizesecurity_button_1" class="p_btn p_btnMnormal" >Arm Stay</div></div>
            </div>
        </div>
        <div class="floatstop"></div>
        <div id="divOrbTextSummary">
            <span class="p_boldNormalTextLarge">Disarmed.&nbsp;All Quiet.</span>
            
        </div>
        
<table class="p_rowl" border=0 cellpadding=0 cellspacing=0 width=325>
<tr><td width=100% class="listBoxData">
<div id="orbSensorsList" style="height:57px;position:relative;overflow:auto;overflow-y:auto;overflow-x:auto;text-align:left;">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr class="p_rowl" style="cursor:pointer;" onmouseover="setbg(this,'p_rowh')" onmouseout="setbg(this,'p_rowl')"><td><table border=0 cellspacing=0 cellpadding=0 width=100%><tr class='p_listRow'><td width="14" style="overflow: hidden;" class='p_iconCellSummary' onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><span class="devStatIcon" title="Last Event: 6/9&nbsp;10:56&nbsp;AM"><canvas icon="devStatOK" class="p_ic_icon_device" width="13" height="13"></canvas><td width=9 onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><img src="/myhome/23.0.0-99/images/spacer.gif" border=0 width=1 height=2></td><td class='p_listRow' onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><a class="p_deviceNameText" href="javascript:launchDetailsWindow('', 672)">Downstairs Gas</a>&nbsp; <span class="p_grayNormalText">Zone&nbsp;13</span></td><td class='p_listRow' valign=middle align=right onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'">Okay&nbsp;</td></tr></tr></table></td></tr>
<tr class="p_rowd" style="cursor:pointer;" onmouseover="setbg(this,'p_rowh')" onmouseout="setbg(this,'p_rowd')"><td><table border=0 cellspacing=0 cellpadding=0 width=100%><tr class='p_listRow'><td width="14" style="overflow: hidden;" class='p_iconCellSummary' onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><span class="devStatIcon" title="Last Event: 9/28&nbsp;8:04&nbsp;AM"><canvas icon="devStatOK" class="p_ic_icon_device" width="13" height="13"></canvas><td width=9 onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><img src="/myhome/23.0.0-99/images/spacer.gif" border=0 width=1 height=2></td><td class='p_listRow' onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><a class="p_deviceNameText" href="javascript:launchDetailsWindow('', 672)">Downstairs Smoke</a>&nbsp; <span class="p_grayNormalText">Zone&nbsp;10</span></td><td class='p_listRow' valign=middle align=right onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'">Okay&nbsp;</td></tr></tr></table></td></tr>
<tr class="p_rowl" style="cursor:pointer;" onmouseover="setbg(this,'p_rowh')" onmouseout="setbg(this,'p_rowl')"><td><table border=0 cellspacing=0 cellpadding=0 width=100%><tr class='p_listRow'><td width="14" style="overflow: hidden;" class='p_iconCellSummary' onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><span class="devStatIcon" title="Last Event: 3/26&nbsp;12:06&nbsp;PM"><canvas icon="devStatOK" class="p_ic_icon_device" width="13" height="13"></canvas><td width=9 onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><img src="/myhome/23.0.0-99/images/spacer.gif" border=0 width=1 height=2></td><td class='p_listRow' onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><a class="p_deviceNameText" href="javascript:launchDetailsWindow('', 672)">Downstairs Window</a>&nbsp; <span class="p_grayNormalText">Zone&nbsp;5</span></td><td class='p_listRow' valign=middle align=right onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'">Closed&nbsp;</td></tr></tr></table></td></tr>
<tr class="p_rowd" style="cursor:pointer;" onmouseover="setbg(this,'p_rowh')" onmouseout="setbg(this,'p_rowd')"><td><table border=0 cellspacing=0 cellpadding=0 width=100%><tr class='p_listRow'><td width="14" style="overflow: hidden;" class='p_iconCellSummary' onClick="launchDetailsWindow('', 24)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><span class="devStatIcon" title="Last Event: Today&nbsp;3:57&nbsp;PM"><canvas icon="devStatOK" class="p_ic_icon_device" width="13" height="13"></canvas><td width=9 onClick="launchDetailsWindow('', 24)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><img src="/myhome/23.0.0-99/images/spacer.gif" border=0 width=1 height=2></td><td class='p_listRow' onClick="launchDetailsWindow('', 24)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><a class="p_deviceNameText" href="javascript:launchDetailsWindow('', 24)">Entry Door</a>&nbsp; <span class="p_grayNormalText">Zone&nbsp;1</span></td><td class='p_listRow' valign=middle align=right onClick="launchDetailsWindow('', 24)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'">Closed&nbsp;</td></tr></tr></table></td></tr>
<tr class="p_rowl" style="cursor:pointer;" onmouseover="setbg(this,'p_rowh')" onmouseout="setbg(this,'p_rowl')"><td><table border=0 cellspacing=0 cellpadding=0 width=100%><tr class='p_listRow'><td width="14" style="overflow: hidden;" class='p_iconCellSummary' onClick="launchDetailsWindow('', 1)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><span class="devStatIcon" title="Last Event: Today&nbsp;5:37&nbsp;PM"><canvas icon="devStatOK" class="p_ic_icon_device" width="13" height="13"></canvas><td width=9 onClick="launchDetailsWindow('', 1)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><img src="/myhome/23.0.0-99/images/spacer.gif" border=0 width=1 height=2></td><td class='p_listRow' onClick="launchDetailsWindow('', 1)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><a class="p_deviceNameText" href="javascript:launchDetailsWindow('', 1)">Family Motion</a>&nbsp; <span class="p_grayNormalText">Zone&nbsp;2</span></td><td class='p_listRow' valign=middle align=right onClick="launchDetailsWindow('', 1)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'">No Motion&nbsp;</td></tr></tr></table></td></tr>
<tr class="p_rowd" style="cursor:pointer;" onmouseover="setbg(this,'p_rowh')" onmouseout="setbg(this,'p_rowd')"><td><table border=0 cellspacing=0 cellpadding=0 width=100%><tr class='p_listRow'><td width="14" style="overflow: hidden;" class='p_iconCellSummary' onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><span class="devStatIcon" title="Last Event: 4/20&nbsp;9:03&nbsp;AM"><canvas icon="devStatOK" class="p_ic_icon_device" width="13" height="13"></canvas><td width=9 onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><img src="/myhome/23.0.0-99/images/spacer.gif" border=0 width=1 height=2></td><td class='p_listRow' onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><a class="p_deviceNameText" href="javascript:launchDetailsWindow('', 672)">Kitchen Heat</a>&nbsp; <span class="p_grayNormalText">Zone&nbsp;12</span></td><td class='p_listRow' valign=middle align=right onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'">Okay&nbsp;</td></tr></tr></table></td></tr>
<tr class="p_rowl" style="cursor:pointer;" onmouseover="setbg(this,'p_rowh')" onmouseout="setbg(this,'p_rowl')"><td><table border=0 cellspacing=0 cellpadding=0 width=100%><tr class='p_listRow'><td width="14" style="overflow: hidden;" class='p_iconCellSummary' onClick="launchDetailsWindow('', 1)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><span class="devStatIcon" title="Last Event: Today&nbsp;5:36&nbsp;PM"><canvas icon="devStatOK" class="p_ic_icon_device" width="13" height="13"></canvas><td width=9 onClick="launchDetailsWindow('', 1)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><img src="/myhome/23.0.0-99/images/spacer.gif" border=0 width=1 height=2></td><td class='p_listRow' onClick="launchDetailsWindow('', 1)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><a class="p_deviceNameText" href="javascript:launchDetailsWindow('', 1)">Master Motion</a>&nbsp; <span class="p_grayNormalText">Zone&nbsp;9</span></td><td class='p_listRow' valign=middle align=right onClick="launchDetailsWindow('', 1)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'">No Motion&nbsp;</td></tr></tr></table></td></tr>
<tr class="p_rowd" style="cursor:pointer;" onmouseover="setbg(this,'p_rowh')" onmouseout="setbg(this,'p_rowd')"><td><table border=0 cellspacing=0 cellpadding=0 width=100%><tr class='p_listRow'><td width="14" style="overflow: hidden;" class='p_iconCellSummary' onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><span class="devStatIcon" title="Last Event: 4/6&nbsp;8:43&nbsp;AM"><canvas icon="devStatOK" class="p_ic_icon_device" width="13" height="13"></canvas><td width=9 onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><img src="/myhome/23.0.0-99/images/spacer.gif" border=0 width=1 height=2></td><td class='p_listRow' onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><a class="p_deviceNameText" href="javascript:launchDetailsWindow('', 672)">Master Window</a>&nbsp; <span class="p_grayNormalText">Zone&nbsp;3</span></td><td class='p_listRow' valign=middle align=right onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'">Closed&nbsp;</td></tr></tr></table></td></tr>
<tr class="p_rowl" style="cursor:pointer;" onmouseover="setbg(this,'p_rowh')" onmouseout="setbg(this,'p_rowl')"><td><table border=0 cellspacing=0 cellpadding=0 width=100%><tr class='p_listRow'><td width="14" style="overflow: hidden;" class='p_iconCellSummary' onClick="launchDetailsWindow('', 1)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><span class="devStatIcon" title="Last Event: Today&nbsp;5:38&nbsp;PM"><canvas icon="devStatOK" class="p_ic_icon_device" width="13" height="13"></canvas><td width=9 onClick="launchDetailsWindow('', 1)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><img src="/myhome/23.0.0-99/images/spacer.gif" border=0 width=1 height=2></td><td class='p_listRow' onClick="launchDetailsWindow('', 1)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><a class="p_deviceNameText" href="javascript:launchDetailsWindow('', 1)">Patio Door</a>&nbsp; <span class="p_grayNormalText">Zone&nbsp;4</span></td><td class='p_listRow' valign=middle align=right onClick="launchDetailsWindow('', 1)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'">Closed&nbsp;</td></tr></tr></table></td></tr>
<tr class="p_rowd" style="cursor:pointer;" onmouseover="setbg(this,'p_rowh')" onmouseout="setbg(this,'p_rowd')"><td><table border=0 cellspacing=0 cellpadding=0 width=100%><tr class='p_listRow'><td width="14" style="overflow: hidden;" class='p_iconCellSummary' onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><span class="devStatIcon" title="Last Event: 10/4&nbsp;5:26&nbsp;PM"><canvas icon="devStatOK" class="p_ic_icon_device" width="13" height="13"></canvas><td width=9 onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><img src="/myhome/23.0.0-99/images/spacer.gif" border=0 width=1 height=2></td><td class='p_listRow' onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><a class="p_deviceNameText" href="javascript:launchDetailsWindow('', 672)">Upstairs Smoke</a>&nbsp; <span class="p_grayNormalText">Zone&nbsp;11</span></td><td class='p_listRow' valign=middle align=right onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'">Okay&nbsp;</td></tr></tr></table></td></tr>
<tr class="p_rowl" style="cursor:pointer;" onmouseover="setbg(this,'p_rowh')" onmouseout="setbg(this,'p_rowl')"><td><table border=0 cellspacing=0 cellpadding=0 width=100%><tr class='p_listRow'><td width="14" style="overflow: hidden;" class='p_iconCellSummary' onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><span class="devStatIcon" title="Last Event: 4/8&nbsp;6:01&nbsp;PM"><canvas icon="devStatOK" class="p_ic_icon_device" width="13" height="13"></canvas><td width=9 onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><img src="/myhome/23.0.0-99/images/spacer.gif" border=0 width=1 height=2></td><td class='p_listRow' onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'"><a class="p_deviceNameText" href="javascript:launchDetailsWindow('', 672)">Upstairs Window</a>&nbsp; <span class="p_grayNormalText">Zone&nbsp;6</span></td><td class='p_listRow' valign=middle align=right onClick="launchDetailsWindow('', 672)" onMouseOver="document.body.style.cursor='pointer'" onMouseOut="document.body.style.cursor='default'">Closed&nbsp;</td></tr></tr></table></td></tr>

</table>
</div>
</tr>
</table>

        <div class="p_divOrbBoxBotMargin"></div>

        <script type="text/javascript">
            adjustButtonLabels();
        </script>
</body>
</html>